const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});
try{
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8088/');
await page.locator('.direction').first().waitFor();
assert.equal(await page.locator('.direction').count(),3);
await page.locator('[data-detail="data"]').click();
assert(await page.locator('#detail-dialog').isVisible());
await page.keyboard.press('Escape');
await page.locator('[data-view="library"]').click();
assert.match(await page.locator('#result-count').textContent(),/514/);
assert.equal(await page.locator('.catalog-card').count(),20);
await page.locator('#query').fill('ch0145');
assert.equal(await page.locator('.catalog-card').count(),1);
assert.match(await page.locator('.catalog-card h3').textContent(),/虚拟助手/);
await page.locator('[data-favorite]').click();
assert.equal(await page.locator('[data-favorite]').getAttribute('aria-pressed'),'true');
await page.locator('#reset-filters').click();
await page.locator('#favorites-only').click();
assert.equal(await page.locator('.catalog-card').count(),1);
await page.locator('#reset-filters').click();
await page.locator('#series-filter').selectOption('创业者早期的烦恼树洞');
assert.match(await page.locator('#result-count').textContent(),/找到 70 篇/);
assert(!((await page.locator('.catalog-card h3').allTextContents()).some(x=>x==='标题：')));
await page.locator('#query').fill('NON_EXISTENT_123');
assert(await page.locator('.empty').isVisible());
await page.locator('[data-reset-filters]').click();
await page.locator('#next-page').click();
assert.equal(await page.locator('#page-count').textContent(),'2 / 26');
await page.locator('[data-view="start"]').click();
await page.locator('[data-select="integration"]').click();
assert.equal(await page.locator('#direction').inputValue(),'integration');
await page.locator('#target').fill('测试用户 <img src=x onerror=alert(1)>');
await page.locator('#evidence').fill('测试记录：某用户每周手动合并三份表格。来源待补，尚未交流。');
await page.locator('#work-hours').fill('3');
await page.locator('#hour-value').fill('100');
await page.locator('#direct-cost').fill('20');
await page.locator('#quote').fill('500');
assert.match(await page.locator('#cost-result').textContent(),/320.00/);
assert.match(await page.locator('#cost-result').textContent(),/180.00/);
assert.equal(await page.locator('#brief img').count(),0);
await page.locator('[name="step0"]').check();
assert.equal(await page.locator('.progress').getAttribute('aria-valuenow'),'1');
await page.reload();
assert.equal(await page.locator('#target').inputValue(),'测试用户 <img src=x onerror=alert(1)>');
assert(await page.locator('[name="step0"]').isChecked());
const downloadP=page.waitForEvent('download');
await page.locator('#export-note').click();
const download=await downloadP;
assert.equal(download.suggestedFilename(),'我的AI副业探索记录.md');
const downloaded=await download.path();
const exported=await require('node:fs/promises').readFile(downloaded,'utf8');
assert(exported.includes('测试记录'));
assert(exported.includes('320.00'));
await page.locator('[data-view="map"]').click();
await page.locator('#combine-who').selectOption('独立开发者');
await page.locator('#combine-form button[type="submit"]').click();
assert.equal(await page.locator('#direction').inputValue(),'custom');
assert.equal(await page.locator('#target').inputValue(),'独立开发者');
assert((await page.locator('#evidence').inputValue()).includes('测试记录'));
page.once('dialog',d=>d.dismiss());
await page.locator('#clear-draft').click();
assert.equal(await page.locator('#direction').inputValue(),'custom');
page.once('dialog',d=>d.accept());
await page.locator('#clear-draft').click();
assert.equal(await page.locator('#evidence').inputValue(),'');
assert.equal(await page.locator('#direction').inputValue(),'');
await page.evaluate(()=>localStorage.clear());
await page.reload();
await page.locator('[data-view="start"]').click();
await page.screenshot({path:path.join(__dirname,'../../assets/desktop-preview.png'),fullPage:true});
for(const width of [390,768]){
await page.setViewportSize({width,height:844});
for(const view of ['start','map','library','lab','sources']){
await page.locator('[data-view="'+view+'"]').click();
const w=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:document.documentElement.scrollWidth}));
assert(w.content<=w.viewport+1,view+' overflows at '+width+': '+JSON.stringify(w));
}
}
await page.locator('[data-view="lab"]').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(__dirname,'../../assets/mobile-preview.png'),fullPage:true});
assert.deepEqual(errors,[]);
console.log('PASS: all views; 514-entry search, series, favorites and pagination; dialog; personal draft reload; escaped input; idea combination; costs; progress; export; clear confirmation; 390px and 768px layouts; no runtime errors.');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});