/* Original Chinese taxonomy and annotations for the pinned upstream inventories. */
window.OSINT_CATALOG = {
  families: [
    {id:'search',name:'搜索与网页资料',mark:'01',intro:'从搜索引擎、网页存档、文档与代码索引中找到公开线索。',effect:'找到已被索引的网页、历史快照或公开文件，建立调查起点。',check:'检索命中不代表资料仍有效；核对原始页面、作者与发布日期。'},
    {id:'identity',name:'账号与社交线索',mark:'02',intro:'按用户名、邮箱、公开资料与社区平台寻找线索。',effect:'发现公开账号、关联线索及社交内容，形成待核对的身份线索。',check:'同名、转发与聚合页面不能直接证明属于同一人；尊重个人隐私。'},
    {id:'infra',name:'域名与网络资产',mark:'03',intro:'查 DNS、证书、IP、公开暴露服务与历史网络记录。',effect:'梳理自有或获授权资产的公开足迹、配置与风险线索。',check:'区分被动查询和主动探测；扫描需先确认权限。'},
    {id:'media',name:'图片、视频与文件',mark:'04',intro:'反向找图、检查元数据、比对视频画面与文件内容。',effect:'寻找素材出处、较早版本、相似画面或文件中的可核实线索。',check:'元数据可以缺失或被修改；单次相似匹配不是来源证明。'},
    {id:'geo',name:'地图与地理核查',mark:'05',intro:'结合地图、街景、卫星影像与公开地理资料。',effect:'定位或交叉核对地点、地貌和影像中的地理特征。',check:'注意影像拍摄时间、地区覆盖、坐标误差与位置敏感性。'},
    {id:'records',name:'公司与公共记录',mark:'06',intro:'查企业登记、公共数据库、新闻、学术资料和统计数据。',effect:'找到组织、人物或事件的原始公开记录及背景资料。',check:'不同地区开放程度不同；记录的更新日期和法律含义需核对。'},
    {id:'breach',name:'泄露与暴露检查',mark:'07',intro:'检查自身或获授权标识是否出现在已公开的泄露资料中。',effect:'发现可能的账号、邮箱或凭据暴露线索，辅助风险响应。',check:'避免上传他人敏感信息；命中、未命中都不等同于完整安全结论。'},
    {id:'dark',name:'Tor 与隐藏服务',mark:'08',intro:'区分隐藏服务搜索、入口目录、隐私访问与技术分析工具。',effect:'在特定索引中寻找隐藏服务线索，或研究其公开可观察属性。',check:'覆盖不完整、镜像可能仿冒；不要向未知站点提交身份与凭据。'},
    {id:'threat',name:'威胁情报与监测',mark:'09',intro:'聚合恶意样本、IP 信誉、攻击活动和威胁组织资料。',effect:'为安全事件调查提供指标、上下文和候选关联。',check:'情报可能过期或误报；用时间、来源和独立证据复核。'},
    {id:'privacy',name:'隐私与研究环境',mark:'10',intro:'浏览器、匿名环境、加密与本地隔离工具。',effect:'降低研究过程中的数据暴露，管理凭据与工作环境。',check:'工具不保证绝对匿名；配置、操作习惯和威胁模型同样重要。'},
    {id:'security',name:'安全测试与取证',mark:'11',intro:'主动扫描、漏洞研究、日志分析、逆向和练习环境。',effect:'在授权范围内测试系统、分析事件与练习技术流程。',check:'这类工具不全是被动 OSINT；执行前确认授权、环境与影响。'},
    {id:'learning',name:'方法、开发与学习',mark:'12',intro:'API、框架、教程、案例、脚本与调查工作流。',effect:'把零散工具组织为可重复的查询、分析、记录与复核流程。',check:'示例命令和“一键安装”先审查来源、依赖、权限及服务条款。'}
  ],
  // Every A top-level section in the extracted inventory has a Chinese purpose.
  a: {
    'General Search':['search','通用搜索','用常见搜索引擎寻找公开网页与新闻入口。'],
    'Google Dorks Tools':['search','高级搜索语法','生成或查阅搜索语法，缩小公开网页检索范围。'],
    'Main National Search Engines':['search','各国本地搜索','通过地区性搜索引擎补充全球引擎的覆盖缺口。'],
    'Meta Search':['search','元搜索','汇集或切换多个搜索来源以比较结果。'],
    'Privacy Focused Search Engines':['privacy','重视隐私的搜索','在不同隐私策略下检索公开网页。'],
    'Data Breach Search Engines':['breach','泄露记录检索','核对邮箱或其他标识是否有公开暴露线索。'],
    'Speciality Search Engines':['search','专业搜索','针对特定信息类型、行业或网络对象检索。'],
    'Dark Web Search Engines':['dark','隐藏服务搜索','从有限的索引寻找 Tor 隐藏服务线索。'],
    'Visual Search and Clustering Search Engines':['search','聚类与可视搜索','把搜索结果按主题或相似性整理。'],
    'Similar Sites Search':['search','相似网站发现','寻找与已知网站相近的站点或替代来源。'],
    'Document and Slides Search':['search','文档与幻灯片','检索公开 PDF、演示文稿和文档。'],
    'Threat Actor Search':['threat','威胁行为者资料','查威胁组织名称、活动和研究报告。'],
    'Live Cyber Threat Maps':['threat','网络威胁地图','观察供应商提供的攻击可视化和趋势。'],
    'File Search':['search','文件搜索','定位可公开访问的特定文件类型。'],
    'Pastebins':['search','公开文本粘贴站','搜索或查看公开发布的短文本线索。'],
    'Code Search':['search','公开代码搜索','在代码托管或代码索引中查项目和公开片段。'],
    'Major Social Networks':['identity','主流社交平台','定位公开资料与平台内线索。'],
    'Real-Time Search, Social Media Search, and General Social Media Tools':['identity','实时与社交搜索','查近期公开帖子、趋势或跨平台内容。'],
    'Social Media Tools':['identity','分平台社交工具','按具体平台查公开账号、帖子和互动。'],
    'Blog Search':['search','博客搜索','查个人或组织的公开文章和观点。'],
    'Forums and Discussion Boards Search':['identity','论坛与讨论区','查公开讨论、用户发言和主题线索。'],
    'Username Check':['identity','用户名核查','查询相同用户名在不同平台上的出现情况。'],
    'People Investigations':['identity','人物公开资料','查公开人物资料和交叉核对入口。'],
    'Email Search / Email Check':['identity','邮箱线索','查公开邮箱关联信息和地址存在性线索。'],
    'Phone Number Research':['identity','电话号码研究','核对号码归属、公开登记或被报告信息。'],
    'Vehicle / Automobile Research':['records','车辆公开记录','按地区查询可合法访问的车辆资料。'],
    'Expert Search':['records','专家搜索','定位研究者、行业专家及其公开成果。'],
    'Company Research':['records','公司研究','查企业登记、组织关系和商业资料。'],
    'Job Search Resources':['records','招聘与岗位信息','从招聘信息了解组织需求和技术栈。'],
    'Q&A Sites':['search','问答社区','查公开问答、解释和问题线索。'],
    'Domain and IP Research':['infra','域名与 IP','查公开注册、解析、证书和网络资产线索。'],
    'Keywords Discovery and Research':['search','关键词研究','扩展查询词、别名和相关主题。'],
    'Web History and Website Capture':['search','网页历史与存档','查看网页过去的公开快照与内容变化。'],
    'Language Tools':['learning','语言工具','翻译、识别或处理跨语言资料。'],
    'Image Search':['media','图片搜索','按图片或关键词寻找相似素材与来源。'],
    'Image Analysis':['media','图片分析','检查图像元数据、内容和编辑痕迹线索。'],
    'Video Search and Other Video Tools':['media','视频搜索与分析','寻找视频出处、关键帧和公开片段。'],
    'Academic Resources and Grey Literature':['records','学术与灰色文献','查论文、机构报告及未正式出版资料。'],
    'Geospatial Research and Mapping Tools':['geo','地理与地图','用地图、影像和地点资料核对位置。'],
    'News':['records','新闻来源','查报道原文与事件时间线。'],
    'News Digest and Discovery Tools':['records','新闻聚合','发现不同媒体对同一事件的报道。'],
    'Fact Checking':['records','事实核查','查已发布核查报告并追溯原始证据。'],
    'Data and Statistics':['records','数据与统计','找公开数据集、统计口径和趋势。'],
    'Web Monitoring':['threat','网页变化监测','跟踪公开页面是否更新或消失。'],
    'Browsers':['privacy','浏览器','选择适合研究和隔离工作的浏览器。'],
    'Offline Browsing':['privacy','离线浏览','保存页面以便断网后阅读或留证。'],
    'VPN Services':['privacy','VPN 服务','管理研究连接路径；不保证匿名。'],
    'Infographics and Data Visualization':['learning','信息图与可视化','将调查资料整理成图表和关系视图。'],
    'Social Network Analysis':['identity','社交网络分析','梳理公开实体和关系；关系仍需证据支持。'],
    'Privacy and Encryption Tools':['privacy','隐私与加密','保护本地资料、通信与凭据。'],
    'DNS':['infra','DNS 查询','核对域名解析、记录和基础设施线索。'],
    'Maritime':['geo','海事公开资料','查船舶、航线和海事位置资料。'],
    'Other Tools':['learning','其他工具','浏览未归入主要分类的候选工具。'],
    'Threat Intelligence':['threat','威胁情报','查指标、风险上下文和安全研究。'],
    'Gaming Platforms':['identity','游戏平台','查游戏平台上的公开账号和资料。'],
    'Music Streaming Services':['identity','音乐平台','查音乐平台上的公开用户资料。'],
    'OSINT Videos':['learning','OSINT 视频','学习调查方法与案例。'],
    'OSINT Blogs':['learning','OSINT 博客','跟进研究者发布的方法和案例。'],
    'OSINT RSS Feeds':['learning','OSINT 订阅源','订阅相关内容更新。'],
    'Other Resources':['learning','其他资料','查工具之外的参考资料。'],
    'Related Awesome Lists':['learning','相关资源清单','转往其他专题的精选目录。']
  },
  // B category number -> [family, Chinese label, intended effect].
  b: {
    1:['identity','用户名与社交账号','按用户名寻找公开账号和数字足迹。'],
    2:['identity','邮箱调查','查邮箱公开关联、投递信息与暴露线索。'],
    3:['identity','电话号码调查','核对号码格式、归属和公开关联线索。'],
    4:['infra','域名与 IP','查证书、DNS、暴露资产和 IP 背景。'],
    5:['geo','地理定位与地图','用地图、影像和地点资料辅助定位。'],
    6:['media','图片与视频','反向查找素材、关键帧及来源。'],
    7:['identity','人脸与人物搜索','从公开人物资料或图像找候选线索。'],
    8:['identity','社交媒体监测','关注公开帖子、品牌或话题变化。'],
    9:['breach','泄露搜索','查询获授权标识的暴露记录。'],
    10:['records','披露与档案平台','查公开档案、泄露报道和文件资料。'],
    11:['security','密码审计工具','在授权环境中测试或恢复凭据。'],
    12:['dark','暗网搜索与工具','区分隐藏服务搜索、目录和分析工具。'],
    13:['privacy','匿名与隐私工具','保护研究环境、通信和本地数据。'],
    14:['security','Web 识别与扫描','识别网站技术并进行授权扫描。'],
    15:['security','社会工程与钓鱼测试','用于授权的安全教育或演练。'],
    16:['security','漏洞扫描与利用','识别和验证授权目标的安全缺陷。'],
    17:['security','网络与无线工具','测绘或测试授权网络与无线环境。'],
    18:['security','移动设备安全','研究获授权设备与移动应用。'],
    19:['learning','AI 辅助调查','用 AI 工具整理、搜索或辅助分析线索。'],
    20:['records','财务与公司资料','查企业、商业关系和公开财务信息。'],
    21:['records','车辆、房产与公共记录','按地区查可合法访问的登记资料。'],
    22:['media','元数据与数字取证','分析文件元数据和数字证据。'],
    23:['infra','摄像头与联网设备','研究公开暴露设备；访问须获授权。'],
    24:['search','高级搜索语法','用查询语法缩小公开网页结果。'],
    25:['breach','凭据与数据搜索语法','研究暴露线索；避免收集他人秘密。'],
    26:['geo','IP 定位链接','查 IP 地址的粗略位置和网络归属。'],
    27:['identity','Telegram 机器人与频道','查公开频道及其提供的调查入口。'],
    28:['identity','俄罗斯地区人物服务','使用地区性公开资料入口。'],
    29:['identity','社交平台搜索','跨平台查公开用户和内容。'],
    30:['security','Termux 工具包','在 Android 终端安装部分安全工具。'],
    31:['security','Kali 工具包','在 Kali 环境组织调查与安全工具。'],
    32:['security','综合安全框架','把多个安全功能放在统一框架中。'],
    33:['security','字典与口令测试','在授权场景准备和测试口令字典。'],
    34:['security','硬件安全','研究固件、无线电或设备接口。'],
    35:['privacy','研究操作系统','选择隔离、取证或隐私研究环境。'],
    36:['learning','OSINT API','以程序接口接入外部数据源。'],
    37:['learning','浏览器扩展','把查询和留证辅助功能放入浏览器。'],
    38:['learning','学习资源','学习公开来源调查方法。'],
    39:['learning','相关 GitHub 仓库','找到其他工具集和专题项目。'],
    40:['learning','安装脚本','按工作流安装工具；先审查脚本。'],
    41:['learning','快速参考清单','快速认识上游挑选的常用工具。'],
    42:['security','红队与攻防','在授权范围内进行攻防演练。'],
    43:['threat','蓝队与防御','监控、检测和响应安全事件。'],
    44:['threat','威胁情报平台','汇聚指标、活动和关联分析。'],
    45:['security','取证与逆向','分析系统痕迹、文件和恶意软件。'],
    46:['learning','训练与 CTF','在练习环境学习安全和调查技能。'],
    47:['learning','漏洞奖励平台','查授权测试项目与规则。'],
    48:['learning','学习资料','查课程、教程和调查方法。'],
    49:['learning','补充工具','浏览上游追加的多领域资源。'],
    50:['records','格鲁吉亚专题资料','查该地区的公开登记、新闻和数据入口。']
  },
  // These priorities are an inference from this repository's research and publishing work.
  opportunities: [
    {
      number:'01', priority:'建议先做', title:'上游项目变更雷达',
      reason:'你持续研究外部 GitHub 项目，固定提交能说明“当时是什么”，但不提醒 README、许可证或演示入口后来发生了什么。',
      outcome:'可形成一份“哪些研究要重看”的变更清单，并保留关键页面的时间点证据。',
      moment:'收录新项目后，关注 README、Release、LICENSE 和关键说明页。',
      limit:'监测只提示发生变化，是否影响原结论仍需人工复核。',
      resources:[['A','ChangeDetection.io'],['A','Wayback Machine'],['A','Hunchly']],
      official:['页面变化监测的原项目说明','https://github.com/dgtlmoon/changedetection.io']
    },
    {
      number:'02', priority:'建议先做', title:'自有网页与 VPS 暴露面自查',
      reason:'仓库已有研究网页和个人代理架构研究；域名、证书与服务可能被第三方公开索引收录，而自己平常不会逐项查看。',
      outcome:'可形成自有域名、证书、公开服务和历史扫描记录的核对表，发现不预期的公开入口。',
      moment:'给网页接自有域名、上线 VPS 服务或调整网络配置后。',
      limit:'只核对自己或获授权的资产；索引可能滞后。向 urlscan 提交网址前先确认可见性。',
      resources:[['B','crt.sh'],['B','Censys'],['B','urlscan.io']],
      official:['Censys 资产与证书查询说明','https://docs.censys.com/docs/platform-quickstart-guide']
    },
    {
      number:'03', priority:'建议先做', title:'发布前的密钥与泄露检查',
      reason:'配置范例、终端记录和网页源码容易夹带令牌或私人地址；问题往往在发布后才被发现。',
      outcome:'可形成疑似密钥位置清单，并检查自己的邮箱是否出现在已收录的泄露事件中。',
      moment:'准备提交配置、截图、日志、自动化脚本或新演示时。',
      limit:'扫描会有误报和漏报；发现真实密钥时应撤销或轮换，不要把秘密上传到陌生查询站。',
      resources:[['B','gitleaks'],['B','Have I Been Pwned'],['A','GitHub Code Search']],
      official:['Gitleaks 的原项目说明','https://github.com/gitleaks/gitleaks']
    },
    {
      number:'04', priority:'高相关', title:'图片与视频的来源链',
      reason:'这个仓库要求说明图片来源和许可；相似图、旧版本截图与文件元数据能帮助查出处，但常被当成设计素材搜索而忽略。',
      outcome:'可形成素材来源卡：原始链接、较早可见版本、元数据线索、实际许可与引用方式。',
      moment:'加入上游截图、示意图参考、视频帧或音乐封面之前。',
      limit:'反向搜索的“最早发现”不是首次发布；找到图片也不等于获得使用许可。',
      resources:[['A','TinEye'],['A','ExifTool'],['B','InVID']],
      official:['TinEye 对反向搜索与许可的说明','https://help.tineye.com/article/265-tineye-tutorial']
    },
    {
      number:'05', priority:'按需使用', title:'第三方工具的准入评估',
      reason:'第二个仓库列出大量一键安装与安全工具。比起先装来试，先核对来源、文件哈希、公开检测与依赖更适合你的研究仓库。',
      outcome:'可形成一张工具准入记录：来源、版本、许可证、安装行为、公开风险线索和是否值得复现。',
      moment:'准备运行陌生脚本、下载二进制文件或引用某个“安全工具”时。',
      limit:'公开检测没有告警不等于安全；不要把私有代码或文件提交到标准公共扫描入口。',
      resources:[['B','VirusTotal'],['A','MalwareBazaar'],['B','urlscan.io']],
      official:['VirusTotal 私密扫描与普通扫描的区别','https://docs.virustotal.com/docs/private-scanning']
    },
    {
      number:'06', priority:'按需使用', title:'项目、组织与域名关系图',
      reason:'当多个项目共享作者、公司、域名或依赖时，列表很难看出关系；公开登记和结构化资料可帮助追溯。',
      outcome:'可形成带证据链接的实体关系图，用于理解项目生态和排查同名混淆。',
      moment:'比较同类项目、研究维护组织或梳理多来源线索时。',
      limit:'同名或共同出现不能直接证明控制、合作或归属；每条关系边都要记录原始出处。',
      resources:[['A','OpenCorporates'],['B','Wikidata'],['A','Gephi']],
      official:['Gephi 的关系网络分析说明','https://gephi.org/desktop/']
    }
  ],
  // Individually written effect notes. Source URLs resolve from inventory.json.
  highlights: [
    ['A','Google Search','search','检索公开网页，快速确定关键词、已知事实和可追溯原站。','搜索排序与收录范围会变化。'],
    ['A','Wayback Machine','search','查看网页历史快照，比较公开页面过去的内容。','未保存的页面无法从存档中恢复。'],
    ['A','Google Hacking Database (GHDB)','search','参考已整理的高级搜索查询，发现公开索引中的特定页面类型。','查询命中不代表有测试或访问权限。'],
    ['B','DocumentCloud','search','检索和阅读公开文档，便于对照原始材料。','核对上传者、文档来源和版本。'],
    ['B','Sherlock','identity','根据用户名查多个平台是否存在同名账号。','同名命中不能证明账号归属。'],
    ['B','Maigret','identity','扩展用户名跨站检索并汇总候选公开账号。','站点检测规则可能失效或误报。'],
    ['B','WhatsMyName','identity','按用户名查看多个网站上的候选账号。','需要回到每个平台核对资料。'],
    ['B','Holehe','identity','根据邮箱检查部分服务的注册线索。','结果不完整，也可能触及隐私边界。'],
    ['B','crt.sh','infra','检索公开证书透明度记录，发现域名与子域名线索。','证书出现不代表主机目前在线。'],
    ['B','Shodan','infra','搜索其索引中的联网设备与服务信息。','索引可能滞后；主动访问需授权。'],
    ['B','Censys','infra','查互联网资产、证书和服务的公开测绘结果。','以平台更新时间和授权范围为准。'],
    ['B','SecurityTrails','infra','查看域名、DNS 或历史基础设施信息。','历史记录不一定反映当前配置。'],
    ['A','Google Lens','media','用图片找相似画面、商品或可能的出处。','视觉相似不等于同一原图。'],
    ['A','TinEye','media','反向检索图片的公开出现位置和版本。','没有结果不代表图片从未发布。'],
    ['B','ExifTool','media','读取文件元数据，寻找设备、时间或编辑线索。','元数据可被删除或篡改。'],
    ['B','InVID','media','辅助拆分视频关键帧并寻找公开出处。','仍须核对上传时间和画面背景。'],
    ['B','OpenStreetMap','geo','查看开放地图要素、道路和地名，辅助地点核查。','地图要素完整度随地区不同。'],
    ['A','Google Earth','geo','对照地形、建筑与卫星影像寻找地点线索。','影像日期与地面现状可能不一致。'],
    ['A','Mapillary','geo','查看用户上传的街景影像，补充现场视觉证据。','覆盖不均；注意拍摄日期。'],
    ['A','Sentinel Hub','geo','获取或分析卫星影像，以比较地表变化。','分辨率、云层与授权条件需核对。'],
    ['A','OpenCorporates','records','检索部分地区的企业登记与关联资料。','地区覆盖和登记更新有差异。'],
    ['B','ICIJ Offshore Leaks','records','查公开离岸实体数据中的名称与关联。','同名和数据来源需要进一步核实。'],
    ['B','PACER','records','查询美国联邦法院公开案件记录。','访问条件、费用及法律语境需核对。'],
    ['B','Wikidata','records','跨语言查结构化实体资料及其引用来源。','条目可由社区编辑，追溯引用。'],
    ['B','Have I Been Pwned','breach','检查自己的邮箱是否出现在已收录的泄露事件中。','未命中不等于从未泄露。'],
    ['B','LeakCheck','breach','查询泄露数据中的获授权标识暴露线索。','数据来源、费用和访问条件需核对。'],
    ['B','DeHashed','breach','查泄露资料索引中的账户或域名线索。','只处理有权调查的数据。'],
    ['A','Intelligence X','breach','在其索引中检索公开或已收录的历史资料。','索引来源与结果时效需逐项核对。'],
    ['A','Ahmia','dark','从可访问的搜索入口找部分 Tor 隐藏服务。','搜索覆盖有限，结果可能过时。'],
    ['A','Aleph Open Search','dark','按上游分类检索隐藏服务或相关索引内容。','实际覆盖和可用性未在本项目测试。'],
    ['B','OnionScan','dark','在授权研究中分析隐藏服务的可观察配置。','属于技术分析操作，先确认权限。'],
    ['B','Dark.fail','dark','查上游所列的隐藏服务入口目录。','镜像和链接真伪必须另行确认。'],
    ['B','VirusTotal','threat','查看文件、URL 或域名在平台中的安全分析资料。','提交敏感样本前核对共享策略。'],
    ['B','AbuseIPDB','threat','查 IP 地址的公开滥用报告与信誉线索。','用户报告可能误报或过时。'],
    ['B','Wazuh','threat','在自有环境中收集安全事件并辅助检测响应。','需部署、配置和持续维护。'],
    ['B','Sigma','threat','用通用检测规则描述可疑日志行为。','规则需要适配实际日志与平台。'],
    ['B','Tor Browser','privacy','通过 Tor 网络浏览网站，隔离部分访问路径信息。','匿名效果取决于配置和操作方式。'],
    ['B','Tails','privacy','在临时操作系统中开展重视隐私的研究。','仍需考虑网络、文件和身份操作风险。'],
    ['B','Whonix','privacy','用虚拟机分隔工作环境与 Tor 网关。','隔离效果需要正确配置。'],
    ['B','KeePassXC','privacy','在本地加密保存研究账号和凭据。','主密码、备份与设备安全仍需管理。'],
    ['B','Nmap','security','在获授权网络中识别主机与开放服务。','主动探测可能影响目标或触发告警。'],
    ['B','Nuclei','security','在授权资产上运行规则化安全检查。','模板结果需复核，避免误报。'],
    ['B','Ghidra','security','分析程序二进制文件，理解代码结构和行为。','分析结论需要人工验证。'],
    ['B','Volatility 3','security','分析内存镜像，寻找进程和事件痕迹。','取证需保持样本完整与来源记录。'],
    ['B','OSINT Framework','learning','按调查问题浏览可选资源类型和工具入口。','框架链接是否仍有效需再核对。'],
    ['B',"Bellingcat's Online Investigations Toolkit",'learning','查看公开调查方法与工具分类。','案例方法需要适配具体任务。'],
    ['B','Trace Labs OSINT VM','learning','在预配置研究环境中学习与开展 OSINT 工作。','下载来源、镜像版本与依赖需核验。'],
    ['B','CyberChef','learning','对文本和数据执行编码、解码与格式转换。','敏感数据处理方式需先确认。']
  ]
};
