'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={start:'我的起点',map:'看懂这个库',library:'思路资料库',lab:'我的小试验',sources:'研究与来源'};
const STORAGE='idea-fieldnotes-008-v1';
const defaults={skills:'后端开发，近期主要使用 AI',goal:'income',reach:'public',hoursWeek:'',industry:'',direction:'',target:'',problem:'',output:'',evidence:'',acceptance:'',nextAction:'',workHours:'',hourValue:'',directCost:'',quote:'',step0:false,step1:false,step2:false,step3:false,step4:false};
let saved={},storageIssue='';
try{const raw=localStorage.getItem(STORAGE);if(raw){saved=JSON.parse(raw);if(!saved||typeof saved!=='object'||Array.isArray(saved))throw Error('invalid');}}
catch(e){saved={};storageIssue='无法读取已保存草稿。当前编辑仍可导出。';}
const formData={...defaults};
for(const key of Object.keys(defaults)){const value=saved.form?.[key];if(typeof defaults[key]==='boolean'){formData[key]=value===true;}else if(typeof value==='string'){formData[key]=value.slice(0,key==='evidence'?8000:2500);}}
const validIds=new Set(RESEARCH.chapters.map(c=>c.id));
let favorites=new Set(Array.isArray(saved.favorites)?saved.favorites.filter(x=>validIds.has(x)):[]);
let filters={query:'',series:'',category:'',favorites:false,featured:false,page:1};
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify({version:1,form:formData,favorites:[...favorites]}));$('#storage-status').textContent='草稿已保存到当前浏览器。没有上传；清理浏览器数据会丢失，重要记录请导出。';storageIssue='';}catch(e){storageIssue='当前浏览器无法保存草稿，请使用导出保留记录。';$('#storage-status').textContent=storageIssue;}}
function route(focus=false){let id=location.hash.slice(1)||'start';if(!names[id])id='start';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!=='view-'+id);document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#breadcrumb').textContent=names[id];document.title=names[id]+' · 思路探索台';if(focus){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
function directionCards(){$('#direction-list').innerHTML=RESEARCH.directions.map((d,i)=>'<article class="direction"><span class="direction-num">0'+(i+1)+'</span><div><h3>'+esc(d.name)+'</h3><p>'+esc(d.pain)+'</p><span class="pill">'+esc(d.tag)+'</span><div class="direction-actions"><button class="button small" data-detail="'+d.id+'">看具体交付</button><button class="button small" data-select="'+d.id+'">带入小试验</button></div></div></article>').join('');}
function showDetail(id){const d=RESEARCH.directions.find(x=>x.id===id);if(!d)return;$('#detail-content').innerHTML='<p class="eyebrow">探索方向 / 尚待验证</p><h2>'+esc(d.name)+'</h2>'+[['为什么值得你观察',d.why],['可能服务的人',d.audience],['一次可以交付什么',d.deliverable],['怎样制作小样',d.sample],['去哪里找需求线索',d.find],['第一步怎样验证',d.test],['先写清交付范围',d.boundary]].map(([t,v])=>'<h3>'+t+'</h3><p>'+esc(v)+'</p>').join('')+'<p class="fine">上游启发：'+d.chapters.map(f=>sourceLink(f,f.replace('.md',''))).join(' · ')+'。以上具体试单方案为本研究延伸。</p><button class="button primary" data-select="'+d.id+'">带入小试验</button><hr>';$('#detail-dialog').showModal();}
function applyDirection(id){const d=RESEARCH.directions.find(x=>x.id===id);if(!d)return;formData.direction=id;
if(!formData.target)formData.target=d.audience;
if(!formData.problem)formData.problem=d.pain;
if(!formData.output)formData.output=d.deliverable;
if(!formData.nextAction)formData.nextAction=d.find;
syncForm();updateBrief();persist();if($('#detail-dialog').open)$('#detail-dialog').close();location.hash='lab';toast('已带入探索方向，现有笔记已保留。');}
function renderCatalog(){const q=filters.query.trim().toLocaleLowerCase();const rows=RESEARCH.chapters.filter(c=>(!q||(c.title+' '+c.file+' '+c.category).toLocaleLowerCase().includes(q))&&(!filters.series||c.series===filters.series)&&(!filters.category||c.category===filters.category)&&(!filters.favorites||favorites.has(c.id))&&(!filters.featured||c.featured));const pages=Math.max(1,Math.ceil(rows.length/20));filters.page=Math.min(filters.page,pages);$('#result-count').textContent='找到 '+rows.length+' 篇 / 全部 '+RESEARCH.chapters.length+' 篇 · 收藏 '+favorites.size+' 篇';$('#page-count').textContent=filters.page+' / '+pages;$('#prev-page').disabled=filters.page<=1;$('#next-page').disabled=filters.page>=pages;
$('#catalog').innerHTML=rows.length?rows.slice((filters.page-1)*20,filters.page*20).map(c=>'<article class="catalog-card"><div class="card-meta"><span class="pill">'+esc(c.category)+'</span>'+(c.hasSimulation?'<span class="pill orange">含模拟案例</span>':'')+(c.featured?'<span class="pill blue">重点抽读</span>':'')+'</div><h3>'+esc(c.title)+'</h3><p class="fine">'+(c.series.startsWith('程序')?'副业宝典':'创业问答')+' · '+esc(c.file)+'</p><div class="catalog-actions"><a href="'+esc(c.url)+'" target="_blank" rel="noreferrer">阅读固定版本原文 ↗</a><button class="button small '+(favorites.has(c.id)?'saved':'')+'" data-favorite="'+esc(c.id)+'" aria-pressed="'+favorites.has(c.id)+'" aria-label="'+(favorites.has(c.id)?'取消收藏：':'收藏：')+esc(c.title)+'">'+(favorites.has(c.id)?'已收藏 ✓':'收藏 +')+'</button></div></article>').join(''):'<div class="empty"><h3>暂时没有匹配的章节</h3><p>试试更短的关键词，或清除主题和收藏筛选。</p><button class="button" data-reset-filters>清除筛选</button></div>';}
function resetFilters(){filters={query:'',series:'',category:'',favorites:false,featured:false,page:1};$('#query').value='';$('#series-filter').value='';$('#category-filter').value='';$('#favorites-only').setAttribute('aria-pressed','false');$('#featured-only').setAttribute('aria-pressed','false');renderCatalog();}
const goals={income:'尽快尝试第一笔收入',tool:'做一个有用的小工具',explore:'先找适合自己的方向'};
const reaches={public:'从公开渠道寻找',peers:'同事或开发者朋友',business:'商家或业务人员'};
function syncForm(){for(const key of Object.keys(defaults)){const el=$('#lab-form').elements.namedItem(key);if(!el)continue;if(el.type==='checkbox')el.checked=formData[key];else{el.value=formData[key];if(el.tagName==='SELECT'&&!el.value){el.value=defaults[key];formData[key]=el.value;}}}}
function offerText(){if(!formData.target&&!formData.output)return '先写下“帮谁”和“交付什么”，你的价值主张会逐渐具体起来。';return '我想帮助'+(formData.target||'【待明确的人群】')+'，先交付'+(formData.output||'【待明确的结果】')+'。';}
function getCost(){const keys=['workHours','hourValue','directCost'];if(keys.some(k=>formData[k]===''||!Number.isFinite(Number(formData[k]))||Number(formData[k])<0))return null;return Number(formData.workHours)*Number(formData.hourValue)+Number(formData.directCost);}
function costText(){const total=getCost();if(total===null)return '填完预计工时、时间估值和直接成本后，显示本单的内部成本参考。直接成本为零时请填 0。';let s='内部成本参考：¥'+total.toFixed(2)+'（工时 × 时间估值 + 直接成本）。';if(formData.quote!==''&&Number.isFinite(Number(formData.quote))&&Number(formData.quote)>=0){const delta=Number(formData.quote)-total;s+=' 按拟议报价计算，扣除上述估算成本后'+(delta>=0?'剩余':'不足')+' ¥'+Math.abs(delta).toFixed(2)+'。';}return s+' 未含未填写的税费或其他支出，不是市场报价或收入预测。';}
function suggestedNext(){if(formData.nextAction.trim())return formData.nextAction;if(formData.reach==='peers')return '请一位同事或开发者朋友描述一项重复工作，问清输入与输出。';if(formData.reach==='business')return '与一位你能接触的业务人员聊聊最近反复发生的手工任务。';return '从一个公开社区记下 3 条具体求助，保留问题原话、日期和来源。';}
function updateBrief(){const done=[0,1,2,3,4].filter(i=>formData['step'+i]).length;const direction=RESEARCH.directions.find(d=>d.id===formData.direction);$('#brief').innerHTML='<p class="summary-label">已有能力</p><div class="summary-value">'+esc(formData.skills||'待补充')+'</div><p class="summary-label">当前目标 / 接触方式</p><div class="summary-value">'+esc(goals[formData.goal]||goals.income)+' · '+esc(reaches[formData.reach]||reaches.public)+'</div><div class="offer">'+esc(offerText())+'</div><p class="summary-label">当前方向</p><div class="summary-value">'+esc(direction?.name||(formData.direction==='custom'?'我的其他想法':'暂不选定，先观察'))+'</div><p class="summary-label">已观察到的需求</p><div class="summary-value">'+esc(formData.evidence.trim()?'已填写观察记录，下一步核对具体需求与购买意愿。':'尚未记录真实需求；当前方向仍是待验证的假设。')+'</div><p class="summary-label">接下来只做这一件事</p><div class="summary-value">'+esc(suggestedNext())+'</div>';
$('#cost-result').textContent=costText();$('#progress-fill').style.width=(done*20)+'%';$('.progress').setAttribute('aria-valuenow',String(done));$('#progress-label').textContent='自行记录的探索进度 '+done+' / 5'+(formData.step4?' · 你已标记实际收款':' · 尚未标记实际收款');
$('#next-question').textContent=formData.evidence.trim()?'把你的观察记录带回对话：哪一条问题最具体？对方如何描述当前做法、花费时间和期望结果？':'找一条你看得懂、也有能力处理的公开求助。我们一起判断：问题是否具体、结果能否验收、怎样试着报价。';}
function buildNote(){const date=new Date().toISOString().slice(0,10);const d=RESEARCH.directions.find(x=>x.id===formData.direction);const lines=['# 我的 AI 副业探索记录','', '导出日期：'+date,'研究项目：008 · AI Money Maker Handbook','原库固定版本：'+RESEARCH.sha,'','## 已知条件','- 能力：'+(formData.skills||'待补充'),'- 目标：'+goals[formData.goal],'- 接触人群：'+reaches[formData.reach],'- 每周时间：'+(formData.hoursWeek?formData.hoursWeek+' 小时':'待补充'),'- 行业：'+(formData.industry||'待补充'),'','## 当前假设','方向：'+(d?.name||(formData.direction==='custom'?'我的其他想法':'未选定')),offerText(),'','问题：',formData.problem||'尚待观察','', '## 真实需求与反馈',formData.evidence||'尚未记录','', '## 验收范围',formData.acceptance||'尚待与用户确认','','## 成本估算',costText(),'','## 下一步',suggestedNext(),'','## 自行记录的进展',...['记录了 3 条具体问题及来源','与一位潜在用户确认过实际流程','展示过一个范围明确的小样','讨论过交付、验收与试单报价','实际收到过第一笔款项'].map((x,i)=>'- ['+(formData['step'+i]?'x':' ')+'] '+x),'','## 收藏的资料',...[...favorites].map(id=>{const c=RESEARCH.chapters.find(x=>x.id===id);return '- '+c.title+'：'+c.url;}),'','## 请继续帮我梳理','请依据以上真实条件和观察，帮我筛选一个值得深入的方向，指出还缺少的具体信息，并设计一次范围清楚的小样或付费试单。不要把我的想法当成已经验证的需求。','', '说明：网页为本研究独立制作；上游方案和模拟案例用作灵感，尚未核验经营结果。'];return lines.join('\n');}
function updateCombination(){const who=$('#combine-who').value;const task=$('#combine-task').value;const output=$('#combine-output').value;$('#combination').textContent='为'+who+'处理'+task+'，先交付'+output+'。接下来确认：他们是否反复遇到这个问题，以及现有做法有什么成本。';}
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.detail)showDetail(button.dataset.detail);if(button.dataset.select)applyDirection(button.dataset.select);if(button.dataset.favorite){const id=button.dataset.favorite;if(!validIds.has(id))return;favorites.has(id)?favorites.delete(id):favorites.add(id);persist();renderCatalog();}if(button.hasAttribute('data-reset-filters'))resetFilters();});
$('#close-dialog').addEventListener('click',()=>$('#detail-dialog').close());
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
[...new Set(RESEARCH.chapters.map(c=>c.category))].sort((a,b)=>a.localeCompare(b,'zh')).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;$('#category-filter').append(o);});
$('#query').addEventListener('input',e=>{filters.query=e.target.value;filters.page=1;renderCatalog();});
for(const [id,key] of [['series-filter','series'],['category-filter','category']])$('#'+id).addEventListener('change',e=>{filters[key]=e.target.value;filters.page=1;renderCatalog();});
for(const [id,key] of [['favorites-only','favorites'],['featured-only','featured']])$('#'+id).addEventListener('click',e=>{filters[key]=!filters[key];filters.page=1;e.currentTarget.setAttribute('aria-pressed',String(filters[key]));renderCatalog();});
$('#reset-filters').addEventListener('click',resetFilters);
$('#prev-page').addEventListener('click',()=>{filters.page--;renderCatalog();$('#result-count').scrollIntoView({block:'start'});});
$('#next-page').addEventListener('click',()=>{filters.page++;renderCatalog();$('#result-count').scrollIntoView({block:'start'});});
$('#lab-form').addEventListener('submit',e=>e.preventDefault());
$('#lab-form').addEventListener('input',e=>{const el=e.target;if(!Object.hasOwn(defaults,el.name))return;formData[el.name]=el.type==='checkbox'?el.checked:el.value;updateBrief();persist();});
$('#direction').addEventListener('change',e=>{const d=RESEARCH.directions.find(x=>x.id===e.target.value);if(d)applyDirection(d.id);else{formData.direction=e.target.value;updateBrief();persist();}});
$('#export-note').addEventListener('click',()=>{const blob=new Blob([buildNote()],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='我的AI副业探索记录.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('探索记录已导出，可带回对话继续讨论。');});
$('#copy-note').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(buildNote());toast('已复制。粘贴到当前对话，我们继续梳理。');}catch(e){toast('浏览器暂不支持复制，请使用“导出探索记录”。');}});
$('#clear-draft').addEventListener('click',()=>{if(!window.confirm('清空当前浏览器中的个人草稿和收藏？建议先导出重要记录。'))return;Object.assign(formData,defaults);favorites.clear();syncForm();updateBrief();renderCatalog();persist();toast('已清空草稿与收藏，恢复本次对话的已知起点。');});
$('#combine-form').addEventListener('input',updateCombination);
$('#combine-form').addEventListener('submit',e=>{e.preventDefault();formData.direction='custom';formData.target=$('#combine-who').value;formData.problem=$('#combine-task').value;formData.output=$('#combine-output').value;syncForm();updateBrief();persist();location.hash='lab';toast('组合想法已带入，下一步补充真实观察。');});
$('.skip-link').addEventListener('click',e=>{e.preventDefault();$('#main').focus();});
window.addEventListener('hashchange',()=>route(true));
directionCards();syncForm();updateBrief();updateCombination();renderCatalog();route();
$('#storage-status').textContent=storageIssue||(saved.form?'已读取当前浏览器的草稿。重要记录请导出保留。':'草稿会保存在当前浏览器；填写内容不会上传。');
