'use strict';
const source=(file,series='程序员的副业赚钱宝典')=>'https://github.com/XiaomingX/ai-money-maker-handbook/blob/'+RESEARCH.sha+'/'+encodeURIComponent(series)+'/'+file;
const upstreamFile=file=>'https://github.com/XiaomingX/ai-money-maker-handbook/blob/'+RESEARCH.sha+'/'+file;
const sourceLink=(file,label,series)=>'<a href="'+source(file,series)+'" target="_blank" rel="noreferrer">'+label+' ↗</a>';
const sectionHead=(eyebrow,title,desc)=>'<div class="page-head"><div><p class="eyebrow">'+eyebrow+'</p><h1>'+title+'</h1><p class="lede">'+desc+'</p></div></div>';
document.querySelector('#view-map').innerHTML=sectionHead('UNDERSTAND THE SOURCE','这个库，能给你什么？','案例收集与思考分析库：围绕痛点、人群、最小产品、获客、收费、留存，发现方向并完善自己的思路。')+
'<div class="stats"><div class="stat"><strong>444</strong><span>副业章节文件</span><p>覆盖技术与非技术方向</p></div><div class="stat"><strong>70</strong><span>创业问答文件</span><p>从找客户到团队经营</p></div><div class="stat"><strong>31</strong><span>首页创业文章外链</span><p>上游列出，未逐一核验</p></div></div>'+
'<p class="fine">按固定提交统计文件数，不等于独立项目数或成功案例数。514 篇索引中有 511 个不同标题。</p>'+
'<div class="panel" id="overview"><h2>一张图看懂：案例、商业思考与方向扩展</h2><p>案例收集与思考分析是原库的本质。沿着痛点、人群、最小产品、获客、收费、留存，扩展图片、文案、音频、直播、绘本等方向。它值得持续整理并产品化为自己的入口，积累个人想法、需求观察与实践反馈，逐步沉淀 AI 产品化思路。</p><a href="./assets/idea-map.png" target="_blank" rel="noreferrer" aria-label="放大查看完整能力总览"><img class="map-diagram" src="./assets/idea-map.png" width="1800" height="2800" alt="案例收集与思考分析库总览：六个商业问题，图片、文案、音频、直播、绘本、视频、工具与知识八类方向，扩展方法及持续迭代的产品化循环。"></a><div class="actions"><a class="button small" href="./assets/idea-map.png" target="_blank" rel="noreferrer">放大查看完整图片 ↗</a><a class="button small" href="./assets/idea-map.png" download="AI副业思路库-完整能力总览.png">下载高清 PNG</a><a class="button small" href="./assets/idea-map.svg" target="_blank" rel="noreferrer">查看矢量 SVG ↗</a></div><p class="fine">本研究独立绘制。图中原库内容与我们的扩展方向分别标明；产品化循环为后续设想，现有 008 功能单独注明。</p></div>'+
'<div class="section-heading"><h2>七种值得提取的能力</h2><span>以下是本研究的归纳</span></div>'+
'<div class="grid-three">'+[
['01 / 扩展视野','发现自己没想到的需求','首页串联 AI 工具、内容、图片、音频和咨询；章节进一步延伸到交易、本地服务和传统行业。价值在于把观察范围拉宽。','<a href="'+upstreamFile('README.md')+'" target="_blank" rel="noreferrer">来源：首页与章节目录 ↗</a>'],
['02 / 连接技术与场景','把能力翻译成客户结果','API、自动化、数据分析等文章把技术放进具体业务里。可以从中提取“谁遇到什么问题、拿到什么结果”的描述。',sourceLink('ch0025.md','API 服务')+' · '+sourceLink('ch0146.md','数据咨询')],
['03 / 拆开商业结构','看见同一能力的多种卖法','定制交付、按次服务、订阅、部署与维护、模板等形式反复出现。可以比较一次交付与持续服务各自需要承担什么。',sourceLink('ch0072.md','Agent 服务')],
['04 / 设计起步方式','从小任务提炼最小交付','部分章节讨论样例、简单流程、人工配合 AI 的服务方式。可以借鉴它们怎样缩小范围，再根据客户输入重新设计。',sourceLink('ch0145.md','自动化虚拟助手')],
['05 / 发现接触点','把获客纳入思路本身','技术教程、社区问题、案例展示、合作推荐等渠道建议，为“去哪里找这种人”提供检索线索。是否能接触到买家仍需观察。',sourceLink('ch0025.md','技术内容与社区')+' · '+sourceLink('ch0444.md','工具配置服务')],
['06 / 理解持续价值','从做出来走向持续有用','文章会讨论任务完成、节省时间、使用频率、留存与维护。可将其转成自己的交付检查项，数值目标需要自己验证。',sourceLink('ch0072.md','交付与价值反馈')],
['07 / 补齐经营问题','让技术之外的问题可见','创业问答涉及目标客户、需求匹配、现金流、合作与团队管理。当前优先阅读找客户与验证问题，其他内容按需回看。',sourceLink('ch0020.md','如何寻找目标客户','创业者早期的烦恼树洞')]
].map(c=>'<article class="capability"><span class="cap-num">'+c[0]+'</span><h3>'+c[1]+'</h3><p>'+c[2]+'</p><div class="fine">'+c[3]+'</div></article>').join('')+'</div>'+
'<div class="section-heading"><h2>让思路继续生长</h2><span>我们的延伸方法</span></div>'+
'<div class="grid-two"><div class="panel"><h3>先拆开，再换一个维度</h3><p>例如“AI 图文创作”可以拆成：帮谁、处理什么输入、用什么能力、交付什么、从哪里找到使用者。</p><ul><li>换人群：面向小商家还是技术作者？</li><li>换任务：生成初稿、整理已有材料，还是检查遗漏？</li><li>换交付：一次结果、批量处理，还是可重复运行的工具？</li><li>换入口：用户在哪里已经表达过困难？</li></ul></div><div class="panel"><h3>拿“表格整理”试着组合</h3><form id="combine-form"><div class="field"><label for="combine-who">给谁</label><select id="combine-who"><option>小型电商运营</option><option>独立开发者</option><option>内容创作者</option><option>小团队行政</option></select></div><div class="form-row"><div class="field"><label for="combine-task">处理什么</label><select id="combine-task"><option>分散表格的字段统一</option><option>公开资料的分类与摘要</option><option>两个系统间的重复录入</option><option>固定格式的周期报告</option></select></div><div class="field"><label for="combine-output">先交付什么</label><select id="combine-output"><option>一份人工复核的结果</option><option>一个可重复运行的脚本</option><option>一次配置与操作演示</option></select></div></div><p id="combination" class="offer"></p><button type="submit" class="button primary">把这个想法带入小试验</button><p class="fine">组合只产生待验证的想法，不代表该人群已有需求。</p></form></div></div>'+
'<div class="callout">阅读时留下两份记录：一份记“这个方向启发了什么”，另一份记“我接触到了什么真实问题”。前者帮助扩展，后者帮助选择。</div>'+
'<div class="panel"><h2>怎样理解文章中的证据</h2><p>本次抽读的第 145、146、443、444、447、448 章均出现“模拟实战”类内容；完整索引机械检测到 183 篇文档带有模拟案例标记。它们可以用于推演过程，涉及的人物和收入不作为已核实成果展示。</p><p>原库首页的“已验证”标题属于作者的表述。我们的研究没有核验其交易、成本和客户记录。仓库的定时工作流只更新时间戳，因此最近提交日期也不能代表内容刚被更新。</p><div class="actions">'+sourceLink('ch0145.md','查看模拟案例出处')+'<a href="'+upstreamFile('.github/workflows/task.yml')+'" target="_blank" rel="noreferrer">查看更新时间工作流 ↗</a></div></div>';

document.querySelector('#view-library').innerHTML=sectionHead('A LIBRARY OF POSSIBILITIES','带着问题，浏览思路。','收录固定版本的 514 篇章节标题与原文入口。先看与你的能力有关的线索，也可以跳出熟悉领域寻找组合。')+
'<div class="panel"><h2>适合当前起点的阅读路线</h2><div class="read-list">'+[
['20','先看：如何找到目标客户','先想办法接触正在遇到问题的人。把“有人求助”与“有人愿意付费”分别记下来。','ch0020.md','创业者早期的烦恼树洞'],
['145','再看：自动化虚拟助手','提取重复任务和小范围服务的思路。文中收益测算与模拟案例不代入个人预期。','ch0145.md'],
['25','接着看：API 接口服务','把接口能力、技术内容与用户入口联系起来；现阶段可缩小到一次对接交付。','ch0025.md'],
['146','对照看：数据分析咨询','借鉴“输入数据→可理解结果”的交付方式。第一步可先限定为清洗与报表。','ch0146.md'],
['444','可选：AI 工具安装与任务演示','如果你已能稳定复现安装与排障，可把配置服务作为另一个观察方向。','ch0444.md']
].map(r=>'<div class="read-item"><span>'+r[0]+'</span><div>'+sourceLink(r[3],r[1],r[4])+'<p>'+r[2]+'</p></div></div>').join('')+'</div></div>'+
'<div class="section-heading"><h2>全部章节索引</h2><span>只收录标题，不复制全文</span></div><div class="filters"><div class="field"><label for="query">搜索关键词或章号</label><input id="query" type="search" placeholder="例如：API、自动化、获客、ch0145"></div><div class="field"><label for="series-filter">资料系列</label><select id="series-filter"><option value="">全部系列</option><option value="程序员的副业赚钱宝典">副业赚钱宝典</option><option value="创业者早期的烦恼树洞">创业者问答</option></select></div><div class="field"><label for="category-filter">主题线索</label><select id="category-filter"><option value="">全部主题</option></select></div></div>'+
'<div class="tally"><button class="tag-button" id="favorites-only" aria-pressed="false">只看我的收藏</button><button class="tag-button" id="featured-only" aria-pressed="false">只看重点抽读</button><button class="tag-button" id="reset-filters">清除筛选</button></div><p class="fine">主题按标题关键词自动归类，仅用于浏览。标记“含模拟案例”来自正文文字检测；无标记不表示已经证实。</p><div class="result-line"><span id="result-count" role="status"></span><span>收藏保存在当前浏览器</span></div><div id="catalog" class="catalog"></div><div class="pager"><button id="prev-page" class="button small">上一页</button><span id="page-count"></span><button id="next-page" class="button small">下一页</button></div>';

document.querySelector('#view-lab').innerHTML=sectionHead('YOUR FIRST SMALL EXPERIMENT','先把一个想法，说具体。','填写真实观察，形成一份可以和我继续讨论的探索记录。草稿只保存在当前浏览器，可导出带回对话。')+
'<p id="storage-status" class="compact-note" role="status">正在读取本地草稿…</p><div class="lab-grid"><form id="lab-form" class="panel">'+
'<div class="form-section"><h3>01 · 我的条件</h3><div class="field"><label for="skills">我能做什么</label><input id="skills" name="skills" maxlength="500"></div><div class="form-row"><div class="field"><label for="goal">当前目标</label><select id="goal" name="goal"><option value="income">尽快尝试第一笔收入</option><option value="tool">做一个有用的小工具</option><option value="explore">先找适合自己的方向</option></select></div><div class="field"><label for="reach">目前如何接触人群</label><select id="reach" name="reach"><option value="public">从公开渠道寻找</option><option value="peers">同事或开发者朋友</option><option value="business">商家或业务人员</option></select></div></div><div class="form-row"><div class="field"><label for="hours-week">每周愿意投入的小时数</label><input id="hours-week" name="hoursWeek" type="number" min="0" max="168" step="0.5" placeholder="暂不确定可留空"></div><div class="field"><label for="industry">熟悉或愿意了解的行业</label><input id="industry" name="industry" maxlength="200" placeholder="例如：开发工具、电商、教育"></div></div></div>'+
'<div class="form-section"><h3>02 · 选一个起点</h3><div class="field"><label for="direction">当前观察方向</label><select id="direction" name="direction"><option value="">还没选，先观察问题</option>'+RESEARCH.directions.map(d=>'<option value="'+d.id+'">'+d.name+'</option>').join('')+'<option value="custom">我的其他想法</option></select></div><div class="field"><label for="target">具体帮谁</label><input id="target" name="target" maxlength="500" placeholder="描述角色与情境，尽量缩小范围"></div><div class="field"><label for="problem">他现在遇到什么问题</label><textarea id="problem" name="problem" maxlength="2500" placeholder="写具体动作、发生频率、当前做法和卡住的地方"></textarea></div><div class="field"><label for="output">我可以先交付什么</label><textarea id="output" name="output" maxlength="2000" placeholder="例如：一类表格的清洗结果、异常清单和操作说明"></textarea></div></div>'+
'<div class="form-section"><h3>03 · 记录公开需求与反馈</h3><div class="field"><label for="evidence">观察到的求助、来源和反馈</label><textarea id="evidence" name="evidence" maxlength="8000" rows="7" placeholder="每条记录：日期 / 人群 / 问题原话 / 来源链接 / 目前怎么解决 / 是否愿意继续聊。先记录，暂不推断购买意愿。"></textarea><small>建议先记 3 条具体问题，再挑一条深入了解。这里不会替你发布或联系任何人。</small></div><div class="field"><label for="acceptance">怎样算交付完成</label><textarea id="acceptance" name="acceptance" maxlength="2000" placeholder="确认输入、输出、正确性检查、修改次数和支持范围"></textarea></div><div class="field"><label for="next-action">下一步只做什么</label><input id="next-action" name="nextAction" maxlength="1000" placeholder="例如：找到一位问题提出者，问清一个真实样例"></div></div>'+
'<div class="form-section"><h3>04 · 做一次自己的成本估算</h3><p class="compact-note">把开发、沟通、测试和修改时间都算上。这是内部成本参考，报价需结合对方需求和交付范围。</p><div class="form-row"><div class="field"><label for="work-hours">本单预计投入（小时）</label><input id="work-hours" name="workHours" type="number" min="0" max="10000" step="0.5"></div><div class="field"><label for="hour-value">你对时间的估值（元/小时）</label><input id="hour-value" name="hourValue" type="number" min="0" max="100000" step="1"></div></div><div class="form-row"><div class="field"><label for="direct-cost">模型与其他直接成本（元）</label><input id="direct-cost" name="directCost" type="number" min="0" max="10000000" step="0.01"></div><div class="field"><label for="quote">准备讨论的报价（元，可留空）</label><input id="quote" name="quote" type="number" min="0" max="10000000" step="0.01"></div></div><p id="cost-result" class="callout"></p></div>'+
'<div class="form-section"><h3>05 · 留下真实进展</h3><div class="checklist">'+[
'记录了 3 条具体问题及来源','与一位潜在用户确认过实际流程','展示过一个范围明确的小样','讨论过交付、验收与试单报价','实际收到过第一笔款项'
].map((x,i)=>'<label><input type="checkbox" name="step'+i+'"><span>'+x+'</span></label>').join('')+'</div><p class="fine">由你按实际情况勾选。联系、试用、报价与收款是不同阶段。</p></div><button class="button" type="button" id="clear-draft">清空我的草稿与收藏</button></form>'+
'<aside class="lab-side"><div class="panel"><p class="eyebrow">MY VALUE BRIEF</p><h2>我的价值草稿</h2><p class="compact-note">随左侧填写更新。现在没有头绪也可以，先留下一个问题。</p><div id="brief"></div><div class="progress" role="progressbar" aria-label="自行记录的探索进度" aria-valuemin="0" aria-valuemax="5" aria-valuenow="0"><span id="progress-fill"></span></div><p id="progress-label" class="fine"></p><div class="actions"><button class="button primary" id="export-note" type="button">导出探索记录</button><button class="button" id="copy-note" type="button">复制给 AI 继续讨论</button></div><p class="fine">网页按你的填写整理内容，没有接入在线 AI。把记录发回当前对话，我可以据此继续帮助你筛选和扩展。</p></div>'+
'<div class="note-card"><h3>下一次，带着一个真实问题回来</h3><p id="next-question">找一条你看得懂、也有能力处理的公开求助。我们一起判断：问题是否具体、结果能否验收、怎样试着报价。</p></div><div class="panel" style="margin-top:22px"><h3>公开渠道观察路线</h3><ol class="steps"><li><strong>选一个能理解的场景</strong><p>例如表格合并、接口同步、AI 工具配置。</p></li><li><strong>搜索问题词</strong><p>在开发者社区、工具项目的公开讨论或垂直行业社区，搜索“求助”“手工”“批量”“同步失败”等。</p></li><li><strong>辨别需求信号</strong><p>看是否有具体输入、重复发生的成本、当前替代做法。点赞和热度仅作线索。</p></li><li><strong>由你决定是否交流</strong><p>先围绕对方的问题交流，确认需求后再约定小样与付费范围。</p></li></ol></div></aside></div>';

document.querySelector('#view-sources').innerHTML=sectionHead('PROVENANCE & RESEARCH NOTES','每个判断，都有来处。','保留原库的思路价值，同时说明哪些来自上游，哪些是我们的归纳，哪些还在等待你的实践。')+
'<div class="panel"><h2>研究范围</h2><table class="source-table"><tbody><tr><th>原始仓库</th><td><a href="https://github.com/XiaomingX/ai-money-maker-handbook" target="_blank" rel="noreferrer">XiaomingX / ai-money-maker-handbook ↗</a></td></tr><tr><th>固定研究提交</th><td><a class="source-code" href="https://github.com/XiaomingX/ai-money-maker-handbook/tree/'+RESEARCH.sha+'" target="_blank" rel="noreferrer">'+RESEARCH.sha+'</a></td></tr><tr><th>研究日期</th><td>2026 年 9 月 28 日</td></tr><tr><th>已做的工作</th><td>读取 README、目录、许可和更新工作流；抽读代表章节；提取全部 514 篇章节标题、文件路径与模拟案例标记；整理能力结构与个人探索方法。</td></tr><tr><th>阅读深度</th><td>全量目录索引 + 代表章节抽读。没有宣称逐篇人工精读全部内容。</td></tr><tr><th>上游许可</th><td>根目录与副业章节目录均为 Apache-2.0。<a href="./UPSTREAM-LICENSE.txt" target="_blank" rel="noreferrer">许可副本 ↗</a> · <a href="./NOTICES.md" target="_blank" rel="noreferrer">来源说明 ↗</a></td></tr><tr><th>网页与图片</th><td>网页、交互、能力归纳、个人试验与总览图由本研究独立制作；不是上游官方产品、截图或经营结果。</td></tr></tbody></table></div>'+
'<div class="grid-two"><div class="panel"><h2>当前对你的价值</h2><p>你已经确认：有后端开发经验、近期主要使用 AI、希望尽快尝试首笔收入、尚无明确人群并希望从公开渠道寻找。</p><p>当前共识是：值得将这个案例与思考库持续整理并产品化，作为自己的 AI 产品化入口。既观察小服务和客户入口，也扩展图片、文案、音频、直播、绘本等方向；用自己的想法、小样与反馈持续完善。时间、预算、行业经历和沟通偏好尚未确认。</p><p>三个建议方向都属于探索假设，优先级来自你的已知条件；尚无真实客户反馈，也没有首单结果。</p></div><div class="panel"><h2>原库、研究与个人记录</h2><ul><li><strong>上游资料：</strong>章节标题、原文和作者提出的方案。</li><li><strong>我们的归纳：</strong>七类能力、主题分类、阅读顺序和思路组合。</li><li><strong>我们的延伸：</strong>三个服务切口、试验流程、成本计算和价值草稿。</li><li><strong>你的实践：</strong>浏览器里填写的需求、反馈与完成情况，可自行导出。</li></ul></div></div>'+
'<div class="panel"><h2>值得保留的细节</h2><ul><li>副业文件编号最高到 448，但实际为 444 篇，文件编号存在缺口，不能按最大编号统计。</li><li>首页只展示了副业系列的一小部分入口，目录中的材料明显更多。</li><li>514 篇文档对应 511 个不同标题，文件总数不代表不重复的创意数量。</li><li>183 篇文档含“模拟实战 / 模拟案例”文字标记；这是一项机械提取结果。</li><li>定时更新工作流只刷新 DATA_UPDATE.md；提交活跃度与内容质量应分别判断。</li><li>部分方向超出 AI 与后端开发；可以作为拓展视野的材料，实施需要相应行业知识。</li></ul></div>'+
'<div class="callout">本页提供灵感研究和个人探索工具。外链中的收入、市场规模、平台规则、工具价格与经营结果未逐项复核，具体采用时再针对所选方向核对。</div>';
